### ISSUE TITLE
requirements-dev.txt wrong requirements.txt path

### ISSUE THREAD

**Issue by matestreitmann** [opencybersecurityalliance/stix-shifter#1307]
**Describe the bug**
The first line of requirements-dev.txt addresses the requirements.txt file for further packages, however requirements.txt is one dir deeper, on stix_shifter/requirements.dev

**To Reproduce**
Run `python3 -m pip install -r requirements-dev.txt`.
You will see the program running into an error of not finding the file requirements.txt

**Expected behavior**
I expected the installation of dependencies to run without errors.

**Desktop (please complete the following information):**
 - OS: WSL 2  Ubuntu 18.0.4.5

**Comment by matestreitmann** [comment]
If this is really unintended behaviour, I would be happy to fix it, if I am wrong about this being an issue than feel free to close it.

**Comment by delliott90** [comment]
It's intended because there is a [generate_requirements script](https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/generate_requirements.py) that combines the requirements.txt along with any module-specific requirement files. The generated requirements file is created at the top level.
