### ISSUE TITLE
x_unique_id mapping missing from from_stix in reaqta connector

### ISSUE THREAD

**Issue by svajipay** [opencybersecurityalliance/stix-shifter#1650]
**Describe the bug**
The mapping for x_unique_id is missing from from_stix. It is mapped to process.id in to_stix and used to identify the process uniquely.

**Comment by DerekRushton** [comment]
@svajipay While we try to map everything we can, there are some scenarios where that isn't possible due to API limitations. It is possible (and common) for API's to return fields that cannot be searched via the API we are using.

Have you verified that this field is supported as a searchable field in the Reaqta API that we are using and if so, can you provide a sample API query that I can use?

**Comment by svajipay** [comment]
The field is not supported by the Reaqta API. I raised a feature request to the Reaqta product to support.

**Comment by DerekRushton** [comment]
In that case I don't think there is anything we can do at the moment, would it be acceptable to close this issue? Once the field is available in the API, we can reopen this (or open a new issue) and we can then address it. 

That said, I have no problem leaving this open provided Reaqta has committed to implementing that feature and has some sort of timeline or indication that the change will be implemented in the near future.

**Comment by svajipay** [comment]
Agree.

**Comment by DerekRushton** [comment]
Sounds good, I'll close this item for now and when/if Reaqta adds support we can take another look.
