### ISSUE TITLE
Dependency problems caused by unused import

### ISSUE THREAD

**Issue by screencoffee** [opencybersecurityalliance/stix-shifter#1720]
Hi,

I'm have run into dependency problens for a project i'm working which utilizes stix-shifter.
One of my other dependencies use `requests-toolbelt==1.0.0`, where stix-shifter needs `requests-toolbelt==0.10.0`

After looking closer at the code base, i noticed that the only place this dependency is imported is in `stix_shifter_utils/stix_transmission/utils/RestApiClient.py`, where it imports `host_header_ssl` but is not used any in the code.
I suspect this might be used in an earlier commit, or possibly left over from development.

Would it be possible either merge #1451 or remove the dependency in its entirety?

**Comment by DerekRushton** [comment]
Can you let me know why you need requests-toolbox updated? I'd like to know where the request is coming from and why it's necessary to make this change.

That said, I don't have any strong opinion against updating the version on the face of it. It'll need a a double check to ensure that it really isn't being used right now. Is there a reason you choose to update the dependency as opposed to removing it? If it's not used it may make sense to remove it completely rather than maintaining a dependency that's not used.

**Comment by screencoffee** [comment]
I'm trying create an integration between our SIEM and Case management system to create artifacts as stix objects, and the SDK used for creating applications is using version 1.0.0. Which creates problems due to the nature of dependency resolution in pip.

The idea of updating it, is because i _might_ have overlooked something, as i'm not that familiar with this codebase.
I did search here on github where the only reference is the one mentioned in my original comment.

**Comment by DerekRushton** [comment]
Understood, When I have a chance I'll take a look into it and see if there are any problems updating/removing the dependency and go from there.

**Comment by benjamin-craig** [comment]
We use to use the request tool belt for SNI checking.  Once we moved to async Python we dropped that functionality.  I can remove this soon.

**Comment by benjamin-craig** [comment]
Merged here: https://github.com/opencybersecurityalliance/stix-shifter/pull/1723/files
